### ISSUE TITLE
Is it fine to include manymine.enable=true label with the image

### ISSUE THREAD

**Issue by itzg** [illiteratealliterator/manymine#2]
I have a request https://github.com/itzg/docker-minecraft-bedrock-server/issues/157 to include the label `manymine.enable=true` with the image itself to simplify usage on platforms like Synology where they don't expose the setting of container labels in the UI. (I double checked that containers pick up the image labels along with labels set on the container.)

I just wanted to see if you knew of any downsides to enabling that label by default with the image? I think users could exclude a bedrock container from manymine by setting the label `manymine.enable=false`.

**Comment by bongodrum** [comment]
Yeah that should be fine. There can only be one server listening on the 19132 port anyway, so if you're running manymine, it's not like you can also be running other bedrock servers on 19132 as well. The label is just a way for manymine to identify which containers it should be interested in - it then uses the docker api to work out which port it should proxy to.

**Comment by illiteratealliterator** [comment]
Yeah that should be fine. There can only be one server listening on the 19132 port anyway, so if you're running manymine, it's not like you can also be running other bedrock servers on 19132 as well. The label is just a way for manymine to identify which containers it should be interested in - it then uses the docker api to work out which port it should proxy to.

**Comment by itzg** [comment]
Thanks for confirming
