### ISSUE TITLE
docker.sock

### ISSUE THREAD

**Issue by chrisepp** [illiteratealliterator/manymine#3]
is the file /var/run/docker.sock that I see added in your example required for this to work? On the synology device you can not add a file tat area to a docker container.

**Comment by illiteratealliterator** [comment]
Yes, in the current implementation it is required - it's what allows a container to use the Docker API to find other containers. In the case of manymine, it's how it finds the containers that have the manymine label, so it knows where to proxy the client pings.

I don't have a Synology, but the label system is modeled after the way Portainer works, so it's possible you can use guides for Portainer and apply them to manymine. For example, [this guide](https://nashosted.com/setup-and-install-portainer-on-synology-nas/) shows how to install Portainer on a Synology with docker.sock support. Maybe it will work for you?

**Comment by chrisepp** [comment]
Thank you for that. I actually installed Portainer, so much more capable than the Synology GUI but it doesn't mess up the Synology one. It works perfectly so far now, thanks!

**Comment by illiteratealliterator** [comment]
That's great, glad it worked for you! 👍
