### ISSUE TITLE
Volume (file / folder) and mount path? 

### ISSUE THREAD

**Issue by keepsmilyn** [illiteratealliterator/manymine#4]
Where should you select the Volume location to install? 

Installation on a Synology NAS with Docker it asks for a Volume (file/folder) location and mount path. 

Furthermore, where does it install by default? Needing to find the configuration file to edit it.

**Comment by keepsmilyn** [comment]
I think I found the right file, but the current contents (after installation is as below). 

Location it was found at was: /var/packages/Docker/etc/manymine.config

CONTENTS: 

`
   "enabled" : true,
   "entrypoint_default" : "docker-entrypoint.sh",
   "exporting" : false,
   "id" : "ed996cb34fb5bece529c8a2d90fe0fa5136c1bc2c3642ea5bf017e554247d38a",
   "image" : "illiteratealliterator/manymine:latest",
   "is_ddsm" : false,
   "is_package" : false,
   "memory_limit_slider" : 6000,
   "name" : "manymine",
   "shortcut" : {
      "enable_shortcut" : false
   }
}
`

**Comment by illiteratealliterator** [comment]
I'm afraid I don't have a Synology, so I don't really know how they work. There was someone else recently that I think got it working though, you can see the issue [here](https://github.com/illiteratealliterator/manymine/issues/3). I linked to a guide I found for getting Portainer working on Synology, and Manymine uses the same kind of setup I believe. Hope it helps.
